-- MySQL Script generated by MySQL Workbench
-- Thu Jul 26 18:30:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `answers_pooling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answers_pooling` ;

CREATE TABLE IF NOT EXISTS `answers_pooling` (
  `id_answer` INT NOT NULL AUTO_INCREMENT,
  `answers` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_answer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Intents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Intents` ;

CREATE TABLE IF NOT EXISTS `Intents` (
  `id_Intents` INT NOT NULL AUTO_INCREMENT,
  `Intents_name` VARCHAR(45) NULL,
  `Intent_link_answer` INT NOT NULL,
  `answers_pooling_id_answer` INT NOT NULL,
  PRIMARY KEY (`id_Intents`, `answers_pooling_id_answer`),
  CONSTRAINT `fk_Intents_answers_pooling`
    FOREIGN KEY (`answers_pooling_id_answer`)
    REFERENCES `answers_pooling` (`id_answer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Intents_answers_pooling_idx` ON `Intents` (`answers_pooling_id_answer` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `answers_pooling`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (1, 'WAMapps is not currently part of EYHelix. WAMapps is bespoke for fund audits.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (2, 'WAMapps was purpose-built by EY to capture data directly from our clients’ administrators. The data capture process is simplified and globally consistent, enabling production of audit-ready workpapers.   The platform uses tools such as EY ISP to automate the valuation process and provide visualizations that can be used to deliver insights beyond the typical audit to boards and client executives.   Watch this one-minute video explainer on how the platform works. ');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (3, 'Send your questions to info.wammaps@ie.ey.com or contact a member of the WAMapps team directly.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (4, 'Outputs produced by WAMapps that will assist at the execution phase of an audit are as follows:\nYear end Leads Sheets – with materiality populated and key items identified\nYear end NAV Based Fee Calculators\nYear end Allocation Testing\nYear End Realised Gain and Loss testing\nYear End Dividend income/expense testing\nYear End Interest income/expense testing\nBook Cost Reconciliation \nInvestment Restrictions Review\nCash leads and cash cut-off testing (pre-year end)\nInvestment leads and stratification workbooks\nYear-End Analytical reviews\nAssistance with Financial Statement review – SOI workbooks and ASC 740 analysis \n');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (5, 'Outputs and conclusions of tests performed will assist audit teams with early identification of SAD items. These outputs are ….\nAdditional visualisations can be used for inclusion in the audit results report. These visualisations are…..\n');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (6, 'Digital innovation and technology advancements are transforming today’s businesses. Our clients are demanding a more robust and forward-looking approach to the audit process. WAMapps positions EY as a digital leader in technology-enabled fund audits. ');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (7, 'Clients do not use or interact with WAMapps directly. WAMapps is a managed service that will be used by our client-facing teams. However, the WAMapps visualizations and insights will be shared with clients as a part of our technology-enabled audit.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (8, 'WAMapps is designed to evolve. Future phases will include other elements of EY’s service model, including tax compliance, regulatory reporting and benchmarking.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (9, 'Outputs produced by WAMapps that may assist at Interim include:\nInterim Leads Sheets – with materiality populated and key items identified\nInterim NAV Based Fee Calculators\nInterim Allocation Testing\nInterim Realised Gain and Loss testing\nInterim Dividend income/expense testing\nInterim Interest income/expense testing\n');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (10, 'WAMapps presents a significant professional development opportunity for our people. The tool eliminates the rote activities of audit and allows our people to focus on risk and providing insight to our clients.\rBy spending more time analyzing the data and focusing on the key risks, our people will have the opportunity to develop as strategic business advisors.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (11, 'Wamapps currently has the following functionalities;\rLead sheets, FS rec, Portfolio, SOI Rec, \rBook cost rec, Analytical Reviews, NAV based fees calculator, Share Capital Rec,\rCash cut off testing, NAV Evolutions, Financial Highlights, Portfolio strat and Sampling, \rASC 740 Analysis, External Evaluations, Rebates Calculation, Exception Reporting, Price Ratio Graphs /Yield. \r\rThe External Evaluations, Rebates Calculation, Exception Reporting, Price Ratio Graphs /Yield functions are connected functions.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (12, 'WAMapps has processed more than 4,500 funds across Ireland and the UK, US and BBC regions. The data platform can support a variety of funds, including hedge funds and regulated/mutual funds.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (13, 'For Budgeting & Resource Planning stage of an audit, WAMapps help automate routine audit processes. These are;');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (14, 'NAV based fee process with WAMapps involve;\n1.	Audit team will need to obtain and review prospectus and agreement to gain understanding of fee structures.\n2.	Monthly and daily NAVs are automatically populated. Management and Admin fee workbooks are prepared. Audit team will need to input the fee rate in these workbooks to recalculate.\n3.	Audit team will need to recalculate performance fee based on the prospectus.\n4.	Audit team will need to agree the recalculated fees to lead.\n');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (15, 'WAM apps enabled:\n1.	Expenses Lead is prepared and referenced to the TB with key items automatically identified\n2.	Dividend and interest income are already discussed above.\n3.	Sub-Ledgers for material non-standard accounts may be requested with items selected for testing upon review\n4.	Audit team will need to obtain details of selected sample.\n');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (16, 'WAMapps enabled unrealised gains and losses are as follows;\n1.	Payables Lead is prepared and referenced to the TB with key items automatically identified\nUnrealised gain/loss balance is reconciled to the movement in unrealised gain/loss per P&L');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (17, 'Training modules are currently under development and will be available shortly.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (18, 'WAMapps is a technology platform that streamlines data capture, fosters greater collaboration and connection among our audit teams, our clients and their administrators. It creates a more interactive and responsive audit that allows us to be more forward-looking and improves the traditional information-sharing process. \r\rThe way we now capture and analyze data gives us a deeper understanding of key risk areas and allows for a consistent focus on business issues. Using WAMapps, we can have more meaningful conversations with our fund clients and provide deeper and more insightful analysis.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (19, 'WAMapps stands for “Wealth and Asset Management applications.” It will encompass a suite of client tools including those for audit, tax and regulatory functions.');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (20, 'The following administrators have already been on-boarded to the platform: IFS, State Street, Citco (Aexeo), HedgeServ, BNY (Advent Geneva) and BNY (InvestOne).');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (21, 'With the use of WAMapps, audit teams are still required to complete the following items for the planning stage of an audit; Assess and identify key areas of risks. Agree and obtain a signed Letter of Engagement Complete independence/ procedures Hold a team planning and estimates event Establish a budget and team structure after taking into account the functionality provided by WAMapps. Hold discussions with your clients about key changes which have occurred during the year Review all board minutes and resolutions Document our understanding of the clients business Determine the nature, timing and extent of audit procedures. In particular, consider what areas can be brought forward for interim testing. Prepare your ASM Complete the planning elements for the following PGAP’s: Going Concern. ');
INSERT INTO `answers_pooling` (`id_answer`, `answers`) VALUES (22, 'As a team review leads and pick out any exceptions or unusual items for investigation (Note: your lead schedules will compare CY to PY balances and highlight the percentage variances) 
																	Your lead schedules will also highlight your significant account balances for testing.\nValuation – where the entire portfolio is valued – Identify exceptions and investigate.Valuation – Portfolio Stratified – As a team, classify securities into grouping and assign Estimation uncertainty by grouping. (Note: privately held positions might not be always be clearly identified on the portfolio. Therefore once groupings have been assigned, review for items that might warrant additional focus). Once stratification has been run and your samples selected, assign the targeted positions to your audit team to value. Requests for additional data should be shared with your TPA at this point.\nFX Rates – The WAMapps output you receive will identify differences between the client rate and an independent rate. Where differences are significant, investigate.
																	\nReconciliations – Check that TPA cash and brokers balances agree to your WAMapps produced cash workbooks by broker and currency. For unusual or reconciling items greater than KIT, obtain explanations on the break from the TPA/Client.\n
																	Review how share classes have performed against each other in the NAV Evolution and incorporate any client benchmarks which ought to be tracked. Where variances are noted, consult with the TPA and/or client to investigate.
																	\nReview the Share Class Reconciliation and ensure that the total of all share classes combined sum to your ending NAV. Variances will be noted already within your WAMapps output.
																	\nFor NAV based fees (management and admin) include fee rates from the client’s latest permanent documents within the WAMapps output received, where significant variances exist, consult with the TPA and/or client to investigate.
																	\nUsing the P&L outputs for Interest, dividends and RGL, run your inbuilt EY MicroStart within the output to select samples for testing. Request support for occurrence from the TPA/Client.
																	\nDocument all queries and differences noted and share immediately with the TPA/Client through the EY Canvas Client Portal.
																	\nFor audit evidence such as Independent Confirmations for Cash, Positions and Transfer Agency; Board Minutes, note whether received or escalate through the appropriate channels to complete.
																	\nAllocate tasks across the team including GDS and set down milestones for achieving closure for each step.');
INSERT INTO `answers_pooling` VALUES (23,'WAMapps enables the following cash and Broker PSP process;\n1.Cash Lead is prepared and referenced to the TB\n2.	Cash Workbook output which includes a breakdown of all individual cash balances by broker and by currency is produced and tied to your lead.\n3. Cash confirmations will still need to be prepared and circularised and compared to the clients year-end balances \n4.	Cash reconciliations will need to be requested and tied to the cash workbook and teams required to test and understand the reasons for selected break items.\n5.	WAMapps prepares a pre-filtered cash work-sheet that allows search for and test unusual cash activity up to ten days before year-end.\n6.	FX rates are independently checked against EY-ISP');
                                          
INSERT INTO `answers_pooling` VALUES(24,'Cash and Broker Reconciliations.\nCounterparty contact details and independent third-party cash confirmations (GDS coordination).\nSupport and explanations for material breaks identified (if any).\nBreakdown and support for post year-end support cash cut-off.');

UPDATE  answers_pooling set answers= '1.	Investment Lead is prepared and referenced to the TB
\n2.	Portfolio output which includes a breakdown of all individual position by investment type and by long/short is produced and tied to your lead 
\n3.	Investment confirmations will still need to be prepared and circularised and compared to the clients year-end balances
\n4.	Position reconciliations will need to be requested and tied to the portfolio workbook and teams required to test and understand the reasons for selected break items
\n5.	Book cost reconciliation is prepared and agreed back to the leads. 
\n6.	Reconcile the unrealised gain/loss balance to the movement in unrealised gain/loss per P&L 
\n7.	Stratify your portfolio. The WAMapps stratification enabler will need to be populated by the audit team. Once populated the tool will provide you with the sample size to test.
\n8.	Equities, listed options, bonds and futures can be priced by WAMapps to EY-ISP. OTC positions and manager priced positions will need to be priced by the audit team.
\n9.	Board meeting minutes and breaches error log will still need to be obtained and reviewed. Investment restrictions tests will be completed on your portfolio listing.'
where id_answer = 25;
									
INSERT INTO `answers_pooling` VALUES (26,'Investments Accounts CAS items include;\nInvestments\nCounterparty contact details and independent third-party confirmations (GDS coordination)\nSupport and explanations for material reconciling breaks Indenified\
									\nBoard meeting minutes \nBreaches and Error Log\nSupport manager priced positions and OTC contracts.');


									
INSERT INTO `answers_pooling` VALUES (27,'WAMapps enables gains and Losses PSP process looks like;\n1.	Realised gain/loss Lead is prepared and referenced to the TB with key items automatically identified\
										\n2.	Realised gain/loss workbook is prepared \n3.	Realised gain/loss workbook is agreed back to your leads\n4.	Within the Realised gain/loss workbook a sample population is selected, and realised gain/loss is recalculated.\
										\n5.	Broker statements for the sample selected will need to be requested from the client and agreed by the audit team.\n6.	Book cost reconciliation is prepared and agreed back to the leads.');

INSERT INTO `answers_pooling` VALUES (28,'CAS items for realised Gains and Losses are; Realised gain/loss.\n Broker statements showing the sample selected.');

INSERT INTO `answers_pooling` VALUES (29,'Wamapps enabled share capital PSP process;\\n1.	Share capital lead will be obtained from your TBA and populated.\n2.	Share register will be agreed to your share capital lead\
										   \n3.	Send and obtain TA confirmation from the Transfer Agent. Once the TA confirmation is received you will need to agree it back to the share capital lead.\n4.	Agree your share capital lead back to your financial statement note disclosure.\
										\n5.	NAV Evolution workbook is prepared. Commentary will need to be included on the on the correlation of the share classes\
										\n6.	An allocation of gains and losses workbook will be prepared by the WAMapps team \n7.	Review of board meeting minutes\n8.	Test for minimum subscriptions\
										\n9.	Send a sample of subs and reds to your TPA and obtain and agree them to bank statements and investor notices.');

INSERT INTO `answers_pooling` VALUES (30,'CAS items for Share capital are;\nShare Capital\nTransfer Agent contact details\nBoard meeting minutes\nBank statement and investor notices support for the subscription and redemptions sample selected');

INSERT INTO `answers_pooling` VALUES (31,'Through WAMapps, the dividend/interest income and expense psp process becomes;\n1.	Dividend and Interest workbook is prepared \n2.	Dividend and Interest workbook is agreed back to your leads\
										\n3.	Determine if you’re taking an analytical or substantive testing approach\n4.	Analytical procedures for dividend/ interest will need to be completed by the audit team\
										\n5.	Within the dividend/interest workbooks a sample population is selected. Coupon and dividend rates are agreed to EY-ISP. The payment date is also verified to EY- ISP\
										\n6.	Sample to test will be selected within your dividend and interest workbooks. Bank statements for the sample selected will from the client and agreed by the audit team.');

INSERT INTO `answers_pooling` VALUES (32,'Here are the CAS items for Dividends/Interest;\1.	Dividend/Interest income & expense\n2.	Bank statements to show dividend and interest payments.');

INSERT INTO `answers_pooling` VALUES (33,'Please see below for the WAMapp enables FSCP process; 
\n1.	WAMapps complete a reconciliation lead for the SOFP and SOCI. Reconciliation of the SOCNA will be completed by the audit team\
\n2.	Within the SOFP and SOCI lead sheets all financial statement adjustments are identified. The audit team will need to reach out to the financial reporting team with a list of the adjustments identified and obtain an understanding of each transaction and when required additional support.\
\n3.	The cash flow statement will be recalculated by the WAMapps team\n4.	The WAMapps team produce a levelling and risk note workbook. \
\nThe audit team will to complete the VaR and     sensitivity analysis review. The offsetting and related parties note will also reviewed by the audit team.Post balance sheet note will be reviewed by the audit teamWAMapps creates a workbook for the financial highlights and Schedule of Investments\
\n5.	The audit team will still need to prepare the disclosure checklists and review the note disclosures to ensure they are in line with applicable accounting standards. You will also need complete clerical accuracy checks and take note of numbers that change between drafts.\
\nIt will be up you to update the workings provided by the WAMapps team on a draft by draft basis if changes occur.');

INSERT INTO `answers_pooling` VALUES(34,'Here are the FSCAP CAS;\n1)	All financial statement adjustments will need to be discussed with the financial reporting team\
\n2)	Obtain support for material adjustments\n3)	Request the client workings netting agreements for the offsetting note\n4)	Workings and additional support when required for the related parties and post balance sheet events disclosures');

INSERT INTO `answers_pooling` VALUES(35,'WAMapp enables receivables process entails;\n1.	Receivables Lead is prepared and referenced to the TB with key items automatically identified\
\n2.	Sub-Ledgers for material non-standard accounts may be requested with items selected for testing upon review\n3.	Dividend and Interest workbook is prepared \n4.	Dividend and Interest workbook is agreed back to your leads\
\n5.	Within the dividend/interest workbooks a sample population is selected. Coupon and dividend rates are agreed to EY-ISP. Dividend and interest is receivable is recalculated.\
\n6.	Audit team will need to obtain list of unsettled trades and unsettled capital transactions and test the sample\n7.	Audit team will need to agree the unsettled trades to broker reconciliations.');

INSERT INTO `answers_pooling` VALUES(36,'Receivables PSP items include;\nDividend/Interest income accrued\nSub-ledgers for unsettled trades, unsettled capital transactions and other material non-standard accounts\
\nBank statements to show subsequent receipts of unsettled trades and unsettled capital transactions.');

INSERT INTO `answers_pooling` VALUES(37,'WAMapps enabled payables process is as follows;\n1.	Payable Lead is prepared and referenced to the TB with key items automatically identified\
										\n2.	Sub-Ledgers for material non-standard accounts may be requested with items selected for testing upon review\n3.	Dividend and Interest workbook is prepared \
\n4.	Dividend and Interest workbook is agreed back to your leads\n5.	Within the dividend/interest workbooks a sample population is selected. Coupon and dividend rates are agreed to EY-ISP. Dividend and interest is payable is recalculated.\n6.	Audit team will need to obtain list of unsettled trades and unsettled capital transactions and test the sample.\
\nAudit team will need to agree the unsettled trades to broker reconciliations.\n7.	Admin and management fees is recalculated. Audit will be required to obtain the agreements and input the rate for NAV based fee calculation and agree the unpaid amount to payable lead.\
\n8.	Audit team will be required to recalculate Performance based fee and agree the unpaid amount to payable lead.\n9.	Audit team will be required to search for unrecorded liabilities.');


INSERT INTO `answers_pooling` VALUES(38,'CAS items for Payables PSP are Dividend/Interest expense accrued.');

UPdate `answers_pooling` set answers = 'CAS items for Payables PSP are;\nDividend/Interest expense accrued\nSub-ledgers for unsettled trades, unsettled capital transactions and other material non-standard accounts\
\nBank statements to show subsequent payments of unsettled trades and unsettled capital transactions \nCash ledger subsequent to the yearend for unrecorded liabilities test.'
where id_answer =38;


INSERT INTO `answers_pooling` VALUES(39,'WAMapps enables income Psp process is as follows;1.	Income Lead is prepared and referenced to the TB with key items automatically identified\
\n2.	Dividend and interest income are already discussed above.\n3.	Sub-Ledgers for material non-standard accounts may be requested with items selected for testing upon review\
');

INSERT INTO `answers_pooling` VALUES(40,'CAS items for PSP income are;\nSub-ledgers for other material non-standard accounts\nSupporting documents for other income selected sample
');


INSERT INTO `answers_pooling` VALUES(41,'Here are the CAS expenses;\n1)	Legal expenses sub-ledger and invoices \n2)	Sub-ledgers for other material non-standard accounts and supporting documents for selected sample\
');


INSERT INTO `answers_pooling` VALUES(42,'WAMapp is designed to assist auditors in the process, none repetitive and more sophisticated tasks that require the professional skills of an auditor and require thought is out of scope for the application. For the planning stage, the audit team stills needs to perform Risk identification, have discussions with clients about changes during the year, review board minutes and documenting our understanding of the business, ASM and PGAP templates.');

INSERT INTO `answers_pooling` VALUES(43,'With the integration of WAMapps into the auditing process, the audit team is still required to complete the following tasks;\
\nReview the lead outputs that WAMapps provides you. \nSend out your PBC listing for support for material balance that will require support and any additional queries you may have as a result of the outputs produced by WAMapps.\
\nIf you are completing existence at interim you will need to prepare and circulate confirmation requests.\nObtain and agree confirmation requests back to your cash and portfolio workbooks.\
');

INSERT INTO `answers_pooling` VALUES(44,'While WAMapps produce a series of outputs to assist in the execution stage of an audit, the team still needs to complete the following tasks during execution;\
A detailed breakdown of the procedures each team are required to execute for each account is discussion in noted on slides X to X\
\nObtain and review your TPA’s SOC1 file (if you are relying on controls)\nFinalise PGAPSs\nReview board minutes\nCompletion of financial statements disclosure checklists\
\nRelated party procedures\nGoing concern assessment\nSubsequent events procedures \nPerform a review on accounting estimates ');

INSERT INTO `answers_pooling` VALUES(45,'For the conclusion of an audit, the team stills requires the following;\nComplete the summary review memorandum \nComplete your Summary Audit Differences templates \nPrepare and obtain signed letters of representation\
\nComplete and discuss the audit results report with the client\nComplete RAS\nDraft and issue signed audit opinion\nArchive the canvas\
');
commit;




-- -----------------------------------------------------
-- Data for table `Intents`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (1, 'EYHelix', 1, 1);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (2, 'Mechanism', 2, 2);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (3, 'FurtherQuestions', 3, 3);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (4, 'Audit_execution_output', 4, 4);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (5, 'Final_output', 5, 5);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (6, 'WAMapp_for_EY', 6, 6);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (7, 'client', 7, 7);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (8, 'Whatnext', 8, 8);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (9, 'Audit_interim_output', 9, 9);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (10, 'For_me', 10, 10);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (11, 'current_functionality', 11, 11);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (12, 'fundstype', 12, 12);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (13, 'planning_WAMoutput', 13, 13);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (14, 'process_NAV_based_fees', 14, 14);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (15, 'process_expense', 15, 15);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (16, 'process_planning', 16, 21);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (17, 'process_unrealised_gains_losses', 17, 16);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (18, 'training', 18, 17);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (19, 'Intro', 19, 18);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (20, 'Abbreviation', 20, 19);
INSERT INTO `Intents` (`id_Intents`, `Intents_name`, `Intent_link_answer`, `answers_pooling_id_answer`) VALUES (21, 'Administrators', 21, 20);
Insert INTO `Intents` values(22,'Process_execution',22,22);
Insert INTO `Intents` values(23,'Process_cashandbroker',23,23);
Insert INTO `Intents` values(24,'CAS_cashandbroker',24,24);
Insert INTO `Intents` values(25,'Process_investments',25,2answers_pooling5);
Insert INTO `Intents` values(26,'CAS_investments',26,26);
Insert into `Intents` values(27,'Process_realized_gains_and_losses',27,27);
Insert into `Intents` values(28,'CAS_realised_gains_losses',28,28);
Insert into `Intents` values(29,'Process_share_capital',29,29);
Insert into `Intents` values(30,'CAS_share_capital',30,30);
INSERT into `Intents` values(31,'Process_dividend_interest',31,31);
INSERT into `Intents` values(32, 'CAS_dividends_interest',32,32);
INSERT into `Intents` values(33,'Process_FSCP',33,33);
INSERT into `Intents` values(34,'CAS_FSCP',34,34);
INSERT into `Intents` values(35,'Process_receivables',35,35);
INSERT into `Intents` values(36,'CAS_receivables',36,36);
INSERT into `Intents` values(37,'Process_Payables',37,37);
INSERT into `Intents` values (38,'CAS_Payables',38,38);
INSERT into `Intents` values(39,'Process_income',39,39);
INSERT into `Intents` values(40,'CAS_income',40,40);
INSERT into `Intents` values(41,'CAS_expense',41,41);
INSERT into `Intents` values(42,'process_planning',42,42);
INSERT into `Intents` values(43,'Procss_interim',43,43);
INSERT into `Intents` values(44,'Process_execution',44,44);
INSERT into `Intents` values(45,'Process_conclusion',45,45);
COMMIT;

update `Intents` set Intents_name = 'Process_planning_out_of_scope' where Intents.id_Intents = 42;